package by.epam.training.javaWEB.finalTask.controller.command;

public enum CommandName {
    LOGIN,
    LOGOUT,
    REGISTRATION,
    GOTO_EDIT_PROFILE,
    SAVE_USER_DETAIL,
    UPDATE_SUPPLIER,
    UPDATE_USER,
    UPDATE_SERVICE,
    UPDATE_PRODUCT,
    SUPPLY_ADDITION,
    PRODUCT_ADDITION,
    SERVICE_ADDITION,
    ADD_ARTICLE,
    SAVE_NEW_USER,
    GOTO_INDEXPAGE,
    GOTO_MAINPAGE,
    ADD_SUPPLIER,
    ADD_PRODUCT,
    SEE_SUPPLIERS,
    SEE_USERS,
    SEE_PRODUCTS,
    SEE_SERVICES,
    ADD_SUPPlY,
    GOTO_REGISTRATION_PAGE,
    GOTO_AUTHORIZATION_PAGE,
    CHANGELOC,
    GOTO,
    ADD_SERVICE,



}
